Simulator generator
HULKs/hulk pull request #1024
Opened 2024-05-18 16:50 UTC by knoellle

## Why? What?

Node execution glue code is automatically generated by our framework for the normal hulk_* binaries.
However, the behavior simulator always used a once copied and since hand maintained approach, which has caused a lot of issues.
This PR removes the manually maintained cycler and replaces it with a generated one.

Other notable changes:
- Moved the behavior simulator from tools to `crates/hulk_behavior_simulator`. Thus it can be used via `pepsi run --target behavior_simulator -- ...`.
- Previously scenarios were changing the `filtered_game_controller_state` directly, but the new cycler executies the `game_controller_state_filter` node which arguably is part of our behavior. The scenarios were adjusted to change the `game_controller_state`.
- Added some basic documentation

Based on #1002 

Fixes #

## ToDo / Known Issues

## Ideas for Next Iterations (Not This PR)

RIIR, Lua bad tbh.

## How to Test

Common pain points with the behavior simulator such as adding/removing/renaming cycle context fields of nodes executed in the behavior simulator should now no longer occur.
Note that when adding an input that isn't currently produced in the behavior simulator, you either have to include the node that produces it in the build.rs or add the output to the fake data node.
But you no longer have to change the cycle context instantiation yourself.

2024-06-01 12:50 UTC, oleflb requested changes

2024-06-01 13:27 UTC, knoellle commented on crates/hulk_behavior_simulator/src/interfake.rs
> +        unimplemented!()
This function is only used by the network cycler, which we don't use in the simulator.
Message passing between robots is done by the simulator directly.

2024-06-01 13:33 UTC, knoellle commented on crates/hulk_behavior_simulator/src/interfake.rs
> +        self.messages.lock().unwrap().push(message);
Because the result type here requires the inner types to be `Send`.
The result type returned from the `Mutex::lock` however is not `Send`.

2024-06-01 13:40 UTC, knoellle commented on crates/hulk_behavior_simulator/src/interfake.rs
> +        take(&mut self.messages.lock().unwrap())
Using parking lot now.

2024-06-01 13:42 UTC, knoellle commented on crates/hulk_behavior_simulator/src/lib.rs
> +pub trait HardwareInterface:
The generated code expects a trait called `HardwareInterface` to exist in the crate.

2024-06-01 13:45 UTC, knoellle commented on crates/hulk_behavior_simulator/src/robot.rs
> +            let source_is_other = *source != self.parameters.player_number;
It is included, but for the sole purpose of generating the structs correctly.
The network cycler is never executed.

2024-06-01 13:47 UTC, knoellle commented on crates/hulk_behavior_simulator/src/server.rs
>  #[allow(clippy::too_many_arguments)]
Removed

2024-06-01 13:48 UTC, knoellle commented on crates/hulk_behavior_simulator/src/robot.rs
> +        let mut cycler2 = Cycler::new(
Whoops, renamed.

2024-06-03 07:57 UTC, oleflb approved these changes
Code looks good to me, works on my machine. Nice work!

2024-06-03 08:01 UTC, merged