RNG Determinism
HULKs/hulk pull request #1042
Opened 2024-05-30 17:37 UTC by knoellle

## Why? What?

What it says.

Why? To make replays more useful.
Currently nodes like line detection and field border detection run use non-deterministic randomness to generate their output.
Thus, when replaying the same vision frame twice, we will likely get two different sets of detected lines.
The random generator state is now stored inside the nodes, making them fully replayable.

Also makes replayer error messages more useful, instead of "failed to replay frame", it will now print the actual root cause.

Fixes #

## ToDo / Known Issues

## Ideas for Next Iterations (Not This PR)

## How to Test

Record data, replay it. 
Look at lines in the image panel, they should no longer jump around when replaying the same vision frame.

2024-05-31 11:11 UTC, schmidma requested changes
one minor thing...

2024-05-31 11:11 UTC, schmidma commented on crates/ransac/src/lib.rs
> +        random_number_generator: &mut ChaChaRng,
```suggestion
        random_number_generator: &mut impl rand::Rng,
```

2024-05-31 12:47 UTC, knoellle commented on crates/ransac/src/lib.rs
> +        random_number_generator: &mut ChaChaRng,
Döne

2024-06-01 13:58 UTC, schmidma approved these changes

2024-06-01 14:01 UTC, merged