openvino 2024.1.0
HULKs/hulk pull request #1048
Opened 2024-06-05 17:28 UTC by oleflb

## Why? What?

Convert to the 2024 version of openvino. It is expected that this change gets rid of the git submodule pain we have with the current openvino version.
With this PR we need a new image with the 2024.1.0 openvino dependency.

Fixes #

## ToDo / Known Issues

- [ ] build new sdk and image
- [ ] test on nao

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test

* Check that code compiles and runs on NAO
* Check that poses are still correct

2024-06-09 12:45 UTC, oleflb commented
wöörks :tada:

2024-06-12 20:01 UTC, schmidma requested changes

2024-06-12 20:01 UTC, schmidma commented on etc/neural_networks/yolov8n-pose-ov.bin
This file seems to be empty now?! What is the change here?

2024-06-12 20:01 UTC, schmidma commented on etc/neural_networks/yolov8n-pose-ov.xml
Did not review any of this file. Can you please summarize what this change is?

2024-06-15 08:38 UTC, oleflb commented on crates/object_detection/src/pose_detection.rs
> +    scratchpad: Box<[f32]>,
I want a structure allocated at runtime but without the ability to resize. This is the mutable version of the more common `Arc<[T]>`. I think this is easier to understand but feel free to object

2024-06-15 08:44 UTC, oleflb commented on etc/neural_networks/yolov8n-pose-ov.bin
Fail on githubs side? File has size of 13MB (binary). It contains the weights of the network and the layout changed with openvino 2024.1.0, requiring this reexport

2024-06-15 08:45 UTC, oleflb commented on etc/neural_networks/yolov8n-pose-ov.xml
This is not handwritten. This file contains the graph structure of the network. Also was reexported with openvino 2024.1.0 since the syntax changed a bit.

2024-06-15 08:46 UTC, oleflb commented on crates/object_detection/src/pose_detection.rs
> +                == 1
done

2024-06-17 11:13 UTC, schmidma approved these changes

2024-06-17 11:18 UTC, merged