Sacrificial nao
HULKs/hulk pull request #1086
Opened 2024-06-30 14:46 UTC by Vivituhh

## Why? What?

Re-enables message sending in `Standby` after referee detection, to enable transition to `Ready` also for robots which do not see referee.
Moreover it implements an sacrificial lamb for the referee pose detection, to avoid penalizing of whole team after false detection.

Fixes #

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test

Test at least with 2 robots (1 detecting, 1 sacrificial lamb at the moment playernumber 3). 
Both should wait 5s after detection (wait for penalty of opponent team), then the lamb transitions to `Ready` and if it is not penalized the others transition to `Ready` 20s after detection.

2024-06-30 15:27 UTC, oleflb commented on crates/control/src/referee_pose_detection_filter.rs
> +    motion_in_standby_count: usize,
switch rows

2024-07-01 13:01 UTC, MaikRe requested changes

2024-07-03 11:41 UTC, MaikRe commented on crates/control/src/sacrificial_lamb.rs
> +                self.motion_in_standby_count = new_motion_in_standby_count;
Nevermind on this, as decrease also accounts for the game controller controller making mistakes which are probably more likely than messages being sent/received in the wrong order

2024-07-03 11:42 UTC, Vivituhh commented on crates/control/src/referee_pose_detection_filter.rs
> +    motion_in_standby_count: usize,
Done

2024-07-03 12:21 UTC, MaikRe commented on crates/control/src/referee_pose_detection_filter.rs
> +    hardware_interface.write_to_network(dbg!(OutgoingMessage::Spl(HulkMessage {
Please no debug

2024-07-03 13:03 UTC, Vivituhh commented on crates/control/src/referee_pose_detection_filter.rs
> +    hardware_interface.write_to_network(dbg!(OutgoingMessage::Spl(HulkMessage {
Done

2024-07-03 13:04 UTC, MaikRe approved these changes
Noice

2024-07-03 13:08 UTC, merged