Expose features flag to pepsi
HULKs/hulk pull request #1102
Opened 2024-07-04 16:42 UTC by ThagonDuarte

## Why? What?

Exposes the `--features <features>` flag of cargo to pepsi. This flag is needed to enable the `ObjectDetectionCycler` when running the replayer.   

Fixes #1095

## How to Test

Run the command:
`$ pepsi run --target replayer --features with_object_detection -- <path to replay log>`

2024-07-06 09:27 UTC, oleflb commented
Does not work when no features are supplied ;)

2024-07-06 14:55 UTC, oleflb requested changes
What do you think of making the argument `Option<&str>` instead? I think that's more verbose compared to checking the string length

2024-07-06 20:53 UTC, knoellle commented
"features" sounds suspiciously plural though. How about a vec or a set? 😉

2024-07-07 11:58 UTC, oleflb approved these changes
Noice #2

2024-07-07 12:04 UTC, merged