disallow instant kicks in penalty shootout and penalty kick
HULKs/hulk pull request #1177
Opened 2024-07-14 09:12 UTC by Vivituhh

## Why? What?

Tests for penalty shootout looked better without instant kicks. In my opinion a little jockeling is fine in this phase.
More small changes to addresses #546.

Fixes #

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*
- [ ] should be tested again on the field

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test
Use GameController in Penalty Shootout with a HULKs striker and compare main against this.

2024-07-14 10:11 UTC, oleflb requested changes
Minor thing, also still requires testing

2024-07-14 10:11 UTC, oleflb commented on crates/control/src/kick_target_provider.rs
> +    let is_penalty_shoot = matches!(
Prefer matching both patterns simultaneously using | and only one matches!

2024-12-18 18:31 UTC, oleflb commented
@Vivituhh do you think we still want this?

2024-12-18 19:11 UTC, Vivituhh commented
If our kicks are better now, we can close this. One could implement it again if needed

2026-07-06 05:31 UTC, closed without merging