refactor `kick_target_provider`, diable obstacle detection for kick off
HULKs/hulk pull request #1241
Opened 2024-07-16 11:21 UTC by Vivituhh

## Why? What?

In last test game the kick off targets were not placed as supposed, because they tried to avoid obstacles. We decided to ignore obstacles in kick off, as no opponent robot is allowed in the center circle. Only own team members are allowed until after the kick and this might also help with the indirect kick rule.

Fixes #

## ToDo / Known Issues

Issue from testgame 16.July.2024

## Ideas for Next Iterations (Not This PR)

none

## How to Test

With game controller test kick off situations and watch kick targets to be placed on the center line and no other kick targets should be changed.

2024-07-16 16:59 UTC, schmidma requested changes

2024-07-16 16:59 UTC, schmidma commented on crates/control/src/kick_target_provider.rs
> +    let (mut kick_opportunities, allow_instant_kicks, respect_obstacles): (Vec<_>, _, _) =
```suggestion
    let (mut kick_opportunities, allow_instant_kicks, respect_obstacles) =
```

2024-07-17 06:17 UTC, Vivituhh commented on crates/control/src/kick_target_provider.rs
> +    let (mut kick_opportunities, allow_instant_kicks, respect_obstacles): (Vec<_>, _, _) =
Done

2024-07-17 06:24 UTC, schmidma approved these changes

2024-07-17 06:29 UTC, merged