Revert WiFi passwords for RC24
HULKs/hulk pull request #1423
Opened 2024-07-31 08:05 UTC by schmidma

## Why? What?

What it says. We should revert back to the rule default, what is also locally deployed in our lab.

2024-07-31 13:33 UTC, julianschuler requested changes

2024-07-31 13:33 UTC, julianschuler commented on crates/constants/src/lib.rs
> +pub const OS_VERSION: &str = "7.5.6";
Please bump the pepsi version too.

2024-07-31 15:01 UTC, schmidma commented on crates/constants/src/lib.rs
> +pub const OS_VERSION: &str = "7.5.6";
Done

2024-08-07 14:21 UTC, julianschuler approved these changes

2024-08-07 14:25 UTC, merged