Twix panel to save automatic calibration values to the repo
HULKs/hulk pull request #1447
Opened 2024-09-16 12:59 UTC by tuxbotix

## Why? What?

Similar functionality to the Manual Calibration panel, subscribes to the additional output from calibration controller and re-use the "save to head" button used elsewhere :)

The design could be improved or merged into the manual calibration panel!

Fixes #

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*

## Ideas for Next Iterations (Not This PR)

* Add statistics, metrics (i.e. RMSE - root mean square error), etc to the panel (after implementing)

## How to Test

Launch twix and open "Automatic camera calibration..." panel. Once calibratiopn process is completed, it should display the values.

2025-04-08 06:49 UTC, alexschmander commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +pub struct AutomaticCameraCalibrationExportPanel {
Perhaps we could drop the `Automatic` in the title of this panel, since it can also be used for exporting the parameters of #1707.

2025-04-09 12:53 UTC, ThagonDuarte commented
@tuxbotix I am currently reviewing this. There are some conflicts with the current main. Could you please rebase it to the current main? Then I can finish my review :)

2025-05-24 10:08 UTC, tuxbotix commented
@ThagonDuarte I'm sorry I didn't see this comment, I've rebased it.

2025-06-05 14:59 UTC, alexschmander commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +            .subscribe_json("Control.additional_outputs.calibration_controller.last_measurements");
The paths here are not correct. 

```suggestion
        let calibration_corrections = nao
            .subscribe_json("Control.additional_outputs.last_calibration_corrections");
        let calibration_measurements = nao
            .subscribe_json("Control.additional_outputs.last_measurements");
```

2025-06-05 15:06 UTC, alexschmander commented on crates/control/src/calibration_controller.rs
> +            });
Why did you need this change? Why use this hidden Option in the `AdditionalOutput` instead of using an `AdditionalOutput<Option<...>>`?

2025-06-05 16:10 UTC, alexschmander commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +    robot_body_rotations: BufferHandle<Vector3<f32>>,
Rename to simplify
```suggestion
    body_rotations: BufferHandle<Vector3<f32>>,
```

2025-06-05 16:10 UTC, alexschmander commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +            robot_body_rotations: body_rotations,
```suggestion
            body_rotations,
```
And rename here too

2025-06-05 16:11 UTC, alexschmander commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +                draw_angles_from_buffer(ui, &self.robot_body_rotations);
```suggestion
                draw_angles_from_buffer(ui, &self.body_rotations);
```
And here as well

2025-06-05 16:14 UTC, alexschmander commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +fn draw_angles(ui: &mut Ui, rotations_degrees: &[f32; 3], sublabel: &str) {
Add empty line between functions here please

2025-06-05 16:36 UTC, alexschmander commented on tools/twix/src/panels/manual_camera_calibration.rs
> +    // yaw -> y
I do not think we need this comment here. Just like the small comments in the following lines.

2025-06-05 16:39 UTC, ThagonDuarte commented
And please bump the twix version for this

2025-06-06 08:31 UTC, tuxbotix commented on crates/control/src/calibration_controller.rs
> +            });
I think it stemmed from https://github.com/HULKs/hulk/issues/1448
I don't like this either, it was either chained unwraps/ flatten or this!.

2025-06-06 08:32 UTC, tuxbotix commented on tools/twix/src/panels/manual_camera_calibration.rs
> +    // yaw -> y
Sure, it can be shorter. I would like to keep one liner comment nearby as rotations are one of the most confusing things in robot transformations.

2025-06-07 14:50 UTC, ThagonDuarte commented on tools/twix/src/panels/manual_camera_calibration.rs
> +    // yaw -> y
Okay fine, i guess a one liner would be fine

2025-06-07 14:55 UTC, ThagonDuarte commented on crates/control/src/calibration_controller.rs
> +            });
Okay, I see. Fine by me then.

2025-06-07 17:59 UTC, tuxbotix commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +pub struct AutomaticCameraCalibrationExportPanel {
Yeah we could, makes the title shorter :D . The naming comes from the calibration controller that automates calibration and this panel helps with the export to repo.

2025-06-08 09:20 UTC, ThagonDuarte requested changes

2025-06-08 09:20 UTC, ThagonDuarte commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +    const NAME: &'static str = "Automatic Calibration";
I just realized, if we rename the struct for the panel we should probably also rename the NAME of it thats displayed in the UI and perhaps also the file name to keep consistency. 
```suggestion
    const NAME: &'static str = "Camera Calibration Export";
```

2025-06-08 09:21 UTC, ThagonDuarte commented
Oh and there is a clippy lint causing the CI to complain :wink:

2025-06-10 08:23 UTC, tuxbotix commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +    const NAME: &'static str = "Automatic Calibration";
Fixed :)

2025-06-10 08:24 UTC, tuxbotix commented
Thank you for the review and suggestions. I was slow to respond as I was on vacation.

P.S. Clippy -> There is an issue in `crates/nao_camera/src/camera.rs` (at least my clippy version) but it wasn't touched in this PR..

2025-06-10 08:26 UTC, tuxbotix commented on tools/twix/src/panels/automatic_camera_calibration_export.rs
> +fn draw_angles(ui: &mut Ui, rotations_degrees: &[f32; 3], sublabel: &str) {
Done. Would have been nice if `cargo fmt` took care of it too :D

2025-06-10 20:19 UTC, ThagonDuarte approved these changes
LGTM

2025-06-10 20:22 UTC, merged