Add taplo format check to CI
HULKs/hulk pull request #1538
Opened 2024-12-18 13:47 UTC by rmburg

## Why? What?

Continuation of #1536 

## ToDo / Known Issues

It's perfect

## Ideas for Next Iterations (Not This PR)

- [ ] update docs

## How to Test

Check CI output

2024-12-18 13:48 UTC, rmburg commented
CI should fail on the first run - TOML files are not yet formatted correctly

2024-12-18 15:53 UTC, schluis requested changes
I like, but please add some documentation

2025-01-09 20:33 UTC, schluis submitted a review, later dismissed
I like it 🐬

2025-01-09 22:52 UTC, schluis approved these changes

2025-01-09 22:55 UTC, merged