Mujoco Walking Engine
HULKs/hulk pull request #1545
Opened 2024-12-22 16:08 UTC by oleflb

## Why? What?
Integrates the walking engine implemented in python into mujoco. Based on #1544 

Fixes #

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test

- Run `uv run scripts/mujoco-walking.py`, observe the Nao walking in the simulation

2025-01-09 16:17 UTC, schluis requested changes
Nice! 🚀  minor things...

2025-01-09 16:17 UTC, schluis commented on tools/machine-learning/mujoco/packages/kinematics/src/kinematics/forward_kinematics.py
> +from walking_engine.walking_types import Side
Please sort and remove unused imports

2025-01-09 16:17 UTC, schluis commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/walking_types.py
> +from transforms import Pose2
Please format

2025-01-09 16:17 UTC, schluis commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/walking.py
> +from .walking_types import State, Measurements, Parameters, Side, Feet, Control
Please sort

2025-01-09 16:17 UTC, schluis commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/ground_provider.py
> +from .walking_types import Side
Please sort

2025-01-09 16:17 UTC, schluis commented on tools/machine-learning/mujoco/scripts/mujoco-walking.py
> +import time
Please sort and remove unused

2025-01-09 16:17 UTC, schluis commented on tools/machine-learning/mujoco/scripts/walking_gym.py
>  from gymnasium.envs.mujoco import MujocoEnv
`"MujocoEnv" is not exported from module "gymnasium.envs.mujoco"
  Import from "gymnasium.envs.mujoco.mujoco_env" instead`

2025-01-09 16:17 UTC, schluis commented on tools/machine-learning/mujoco/scripts/walking_gym.py
>  from gymnasium.spaces import Box
Please sort

2025-01-10 21:49 UTC, oleflb commented on tools/machine-learning/mujoco/packages/kinematics/src/kinematics/inverse_kinematics.py
> +        ankle_roll=np.arcsin(-np.clip(left_foot_rotation_c2[1], -1.0, 1.0)),
because arcsin is not defined for values outside -1,1

2025-01-10 21:49 UTC, oleflb commented on tools/machine-learning/mujoco/packages/kinematics/src/kinematics/inverse_kinematics.py
> +    )[..., 2]
because both of them get the last column from a matrix

2025-01-10 21:50 UTC, oleflb commented on tools/machine-learning/mujoco/packages/robot_dimensions/README.md
done

2025-01-10 21:51 UTC, oleflb commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/walking.py
> +        x.end_feet = end_feet_from_request(u, x, parameters)
yes, the start feet are the last end feet. The next end feet are computed

2025-01-10 21:51 UTC, oleflb commented on tools/machine-learning/mujoco/pyproject.toml
> +readme = "README.md"
done

2025-01-10 21:52 UTC, oleflb commented on tools/machine-learning/mujoco/scripts/mujoco-walking.py
> +        measurements.pressure_right = 0.0
This is not about performance but showcasing that it works. This is replaced by FSRs in next PR

2025-01-10 21:55 UTC, oleflb commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/joint_command.py
> +) -> LegJoints:
done

2025-01-10 21:56 UTC, oleflb commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/joint_command.py
> +from robot_dimensions import ANKLE_TO_SOLE
done

2025-01-10 21:56 UTC, oleflb commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/joint_command.py
> +def joint_command(
done

2025-01-10 21:57 UTC, oleflb commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/ground_provider.py
> +    forget_rotation,
fixed

2025-01-10 21:58 UTC, oleflb commented on tools/machine-learning/mujoco/packages/kinematics/src/kinematics/forward_kinematics.py
> +from walking_engine.walking_types import Side
done

2025-01-10 21:58 UTC, oleflb commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/walking_types.py
> +from transforms import Pose2
done

2025-01-10 21:59 UTC, oleflb commented on tools/machine-learning/mujoco/packages/walking_engine/src/walking_engine/walking.py
> +from .walking_types import State, Measurements, Parameters, Side, Feet, Control
done

2025-01-10 22:03 UTC, oleflb commented on tools/machine-learning/mujoco/scripts/walking_gym.py
>  from gymnasium.envs.mujoco import MujocoEnv
done

2025-01-10 22:03 UTC, oleflb commented on tools/machine-learning/mujoco/scripts/walking_gym.py
>  from gymnasium.spaces import Box
done

2025-01-10 22:35 UTC, oleflb commented on tools/machine-learning/mujoco/scripts/mujoco-walking.py
> +        base_height=0.23,
done

2025-01-10 22:38 UTC, schluis approved these changes

2025-01-10 22:42 UTC, merged