Lookaround
HULKs/hulk pull request #180
Opened 2023-04-05 20:24 UTC by pakonro

… nao leaves penalised or initial state

## Introduced Changes

*Describe here what this pull request does*

Fixes #

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test

*Describe how to test your changes. (For the reviewer)*

2023-04-05 20:40 UTC, h3ndrk commented on etc/configuration/default.json
> +    },
Fucking JSON... 😒

2023-04-22 17:23 UTC, pakonro commented on crates/types/src/configuration.rs
> +    pub initial_lookaround_duration: f32,
Done

2023-04-22 17:23 UTC, pakonro commented on crates/control/src/behavior/node.rs
> +            if now.duration_since(active_since).unwrap().as_secs_f32()
Done

2023-04-22 17:23 UTC, pakonro commented on crates/control/src/behavior/node.rs
> +            if now.duration_since(active_since).unwrap().as_secs_f32()
Done

2023-04-23 10:29 UTC, okiwi6 requested changes
Nice, the changes look good to me. The CI is still failing, please do a `cargo fmt` on your code to format. Also `behavior_simulator` is unable to build since you added `cycle_time` in the behavior context but not in the behavior_simulator context (you can check that it is not working by running `cargo build --manifest-path tools/behavior_simulator/Cargo.toml`.
On a more general note, please fill in the PR description next time :)

2023-04-26 13:48 UTC, okiwi6 requested changes

2023-04-26 13:48 UTC, okiwi6 commented on etc/configuration/default.json
> +
please remove newline

2023-04-26 14:05 UTC, merged