Add MotionType to execute an energy saving stand
HULKs/hulk pull request #194
Opened 2023-04-17 10:58 UTC by schmidma

## Introduced Changes

This introduces a new boolean flag, whether a standing motion should be "energy-saving".
An energy saving stand is executed by an independent motion node, which currently only publishes penalized angles. A normal stand is still done by walking.

Fixes #129 

## ToDo / Known Issues

none

## Ideas for Next Iterations (Not This PR)

- a more sophisticated version which actually uses control to save energy (e.g. gradually decreasing stiffness)
- lean the robot a bit to the front when penalized as it tends to fall backwards much easier than to the front

## How to Test

Testgame? Alternatively deploy the nao as the keeper, as it is standing with energy saving in the goal center without a ball

2023-04-20 18:51 UTC, schmidma commented
successfully tested in today's testgame. We observed some possible improvements, like slightly leaning forward in the standing position, but this may also be improved in future iterations

2023-04-21 07:58 UTC, okiwi6 requested changes
Looks nice, only have two questions and noticed non-alphabetical ordering :)

2023-04-21 07:58 UTC, okiwi6 commented on crates/control/src/motion/energy_saving_stand.rs
> +    pub cycle_time: Input<CycleTime, "cycle_time">,
sort alphabetically?

2023-04-21 07:58 UTC, okiwi6 commented on crates/control/src/motion/energy_saving_stand.rs
> +    pub leg_stiffness: Parameter<f32, "energy_saving_stand.leg_stiffness">,
sort alphabetically?

2023-04-21 07:58 UTC, okiwi6 commented on crates/control/src/behavior/fall_safely.rs
> +    }
Why is this required now?

2023-04-21 07:58 UTC, okiwi6 commented on crates/control/src/behavior/stand_up.rs
> +    }
Why is this required now?

2023-04-26 07:25 UTC, schmidma commented on crates/control/src/motion/energy_saving_stand.rs
> +    pub cycle_time: Input<CycleTime, "cycle_time">,
done

2023-04-26 07:25 UTC, schmidma commented on crates/control/src/motion/energy_saving_stand.rs
> +    pub leg_stiffness: Parameter<f32, "energy_saving_stand.leg_stiffness">,
done

2023-04-26 07:26 UTC, schmidma commented on crates/control/src/behavior/stand_up.rs
> +    }
I don't remember, removed now

2023-04-26 08:11 UTC, okiwi6 approved these changes

2023-04-26 08:14 UTC, merged