Ball interception v2
HULKs/hulk pull request #392
Opened 2023-06-27 09:39 UTC by julianschuler

## Introduced Changes

This PR improves the ball interception by calculating the shortest path for intercepting the ball while considering the robot's current movement.

## ToDo / Known Issues

- [ ] Write tests for geometric functions (`calculate_arc_tangent_to` and `triangle_orientation`)
- [ ] Update the scenario file for testing with the behavior simulator
- [ ] Parameter tuning

## Ideas for Next Iterations (Not This PR)

None.

## How to Test

Flash a NAO or execute the `ball_intercept.lua` scenario in the behavior simulator.

2023-07-04 18:09 UTC, knoellle requested changes

2023-07-05 08:16 UTC, julianschuler commented on crates/types/src/geometry.rs
>  }
Thanks, done.

2023-07-05 08:17 UTC, julianschuler commented on crates/control/src/behavior/intercept_ball.rs
> +        && ball_moving_towards_own_half
Good point, done.

2023-07-05 08:17 UTC, julianschuler commented on crates/control/src/behavior/intercept_ball.rs
> +    let direction = UnitComplex::new(angle_change) * walking_direction;
Good point, done.

2023-07-05 08:17 UTC, julianschuler commented on crates/control/src/behavior/intercept_ball.rs
> +            }
Yes, but this requires a better ball model for the velocity decay so I would propose to do this in another iteration. We could also combine this with "time to reach ball", but this is also not fully finished yet, so I suggest to do this later.

2023-07-05 08:47 UTC, knoellle approved these changes
LGTM

2023-07-05 12:23 UTC, merged