Localization Replay Viewer
HULKs/hulk pull request #498
Opened 2023-07-08 12:50 UTC by knoellle

## Introduced Changes

Adds a new tool at `tools/localizer` which can load and replay log files generated by #468.
It can be controlled the same way as the behavior simulator but only provides the information stored in the log file augmented with line correspondences.
A map layer to show line correspondences is also added to twix.
Tool code is hacky and optimized to reduce code changes elsewhere.

Fixes #

## ToDo / Known Issues

## Ideas for Next Iterations (Not This PR)

Proper replay & viewer

## How to Test

```
cd tools/localizer
cargo run <path-to-localization-log.bincode>
```
- Open twix, map panel, behavior simulator panel, connect to localhost, turn on line correspondences.
- Gaze upon the robots path and be delighted.

2023-07-13 07:15 UTC, h3ndrk requested changes

2023-07-13 07:15 UTC, h3ndrk commented on tools/twix/src/panels/map/layers/line_correspondences.rs
> +    const NAME: &'static str = "Line Associations";
```suggestion
    const NAME: &'static str = "Line Correspondences";
```

2023-07-13 07:15 UTC, h3ndrk commented on tools/localizer/src/main.rs
Where can I find a localization log file to test this with?

2023-07-13 17:19 UTC, h3ndrk submitted a review, later dismissed
Wörks

2023-07-14 22:59 UTC, knoellle commented on tools/twix/src/panels/map/layers/line_correspondences.rs
> +    const NAME: &'static str = "Line Associations";
Done

2023-07-15 06:15 UTC, h3ndrk approved these changes

2023-07-15 06:17 UTC, merged