Behavior simulator ball model
HULKs/hulk pull request #511
Opened 2023-07-14 22:55 UTC by knoellle

## Introduced Changes

On main, the behavior simulator is in a soft-broken state since robots keep losing the ball when they become striker.
This is because they look too far left and right of the ball without having a ball model. That means they immediately lose the ball once it leaves their field of view.

This PR both fixes the simulated glance angle as well as introducing a simplified ball model.
As opposed to the real world, the robot's ball model keeps getting updates with the true position of the ball for some time after the ball leaves the field of view of the robot.
In the real world, noisy percepts are filtered and a physical model is applied to simulate movement of the ball when it is not seen.
In this implementation, a robot would be able to detect a change of the ball's velocity, e.g. due to a kick, without the ball currently being inside the field of view.
This saves us from having to keep separate ball models for each robot that would be updated by simulated percepts and while also simulating the ball physics.
I think this is a reasonable simplification. 

Fixes #

## ToDo / Known Issues

## Ideas for Next Iterations (Not This PR)

## How to Test

Run any scene in the behavior simulator, e.g. golden goal.
The robots should be able to score goals again without requiring half a dozen striker switches.

2023-07-16 15:12 UTC, h3ndrk requested changes

2023-07-16 15:12 UTC, h3ndrk commented on tools/behavior_simulator/src/state.rs
> +                    now.duration_since(last_seen).expect("Time ran backwards")
Non capitalized error messages

2023-07-28 15:41 UTC, knoellle commented on tools/behavior_simulator/src/state.rs
> +                        + f * robot.parameters.look_at.glance_angle
Done

2023-07-28 15:41 UTC, knoellle commented on tools/behavior_simulator/src/state.rs
> +                    now.duration_since(last_seen).expect("Time ran backwards")
Done

2023-07-29 05:10 UTC, h3ndrk approved these changes

2023-07-29 05:17 UTC, merged