Ball Rest Prediction
HULKs/hulk pull request #599
Opened 2023-10-21 17:03 UTC by knoellle

## Introduced Changes

Attempts to calculate where the ball will come to rest.
Disclaimer: The model for this is currently not very accurate, feel free to suggest improvements.

This prediction is then used for the kick target calculations and thus also for time-to-reach calculations.
In theory this should allow for faster striker switching when the ball is kicked past the current striker and towards our defense.

Fixes #

## ToDo / Known Issues

## Ideas for Next Iterations (Not This PR)

## How to Test

2023-10-22 08:32 UTC, knoellle commented
Musste die Ballposition wohl doch durch den Ballzustands- und Weltzustandskomponisten schieben.
Zweig neu geerdet auf `haupt` und die kontinuierlichen Integrationsprüfungen repariert.
Bereit zur Neuansicht.

2023-11-08 15:59 UTC, okiwi6 requested changes
Left some remarks, I would also like if this feature could be easily turned on/off from `default.json`.

2023-11-08 15:59 UTC, okiwi6 commented on tools/behavior_simulator/src/state.rs
> +                        // TODO: Simulate this properly
todo? :)

2024-12-04 16:11 UTC, oleflb commented
We decided that this did not bring us any advantage and this branch is very outdated as the ball filter was rewritten 2 times over since this PR was recreated

2024-12-04 16:11 UTC, closed without merging