2.0 * PI is changed to TAU
HULKs/hulk pull request #653
Opened 2023-12-12 21:23 UTC by MeiiMoon

## Introduced Changes

2.0 * PI is changed to TAU

## How to Test

Check whether all 2.0 * PI is changed to TAU.

2023-12-20 17:15 UTC, fried777 requested changes
There are some PI * 2 left. For example in twix_painter.rs in 292 and 303. Maybe check for all occurrences of PI, since equations might span several lines or change order. Thank you for the pull request!

2023-12-20 17:15 UTC, fried777 commented on inspect.lua
> +return inspect
Does this belong here?

2024-01-12 11:54 UTC, MeiiMoon commented on inspect.lua
> +return inspect
Now it is fixed.

2024-01-17 15:00 UTC, fried777 approved these changes

2024-01-17 15:04 UTC, merged