Bump egui
HULKs/hulk pull request #655
Opened 2023-12-19 16:46 UTC by okiwi6

## Introduced Changes

This PR bumps the egui version to 0.24.
It also removes the fork of egui-dock from @knoellle since his changes got merged.
Upgrading egui-dock to the newest egui version also brought some fancy new features into twix.

Fixes #

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test

* make sure twix still works

2024-01-04 17:57 UTC, knoellle requested changes
Looks good for the most part, I left some minor remarks.

2024-01-04 17:57 UTC, knoellle commented on tools/twix/src/main.rs
> +    tree: DockState<Tab>,
rename member to `dock(_state)`?

2024-01-04 17:57 UTC, knoellle commented on tools/twix/src/panels/image/mod.rs
> +        // let image_rect = Rect::from_min_size(image_response.rect.left_top(), displayed_image_size);
Remove these comments

2024-01-09 19:05 UTC, okiwi6 commented on tools/twix/src/main.rs
> +    tree: DockState<Tab>,
done

2024-01-09 19:05 UTC, okiwi6 commented on tools/twix/src/panels/image/mod.rs
> +        // let image_rect = Rect::from_min_size(image_response.rect.left_top(), displayed_image_size);
done

2024-01-10 13:46 UTC, knoellle approved these changes
LGTM

2024-01-10 13:49 UTC, merged