Hybrid alignment fix
HULKs/hulk pull request #768
Opened 2024-03-23 15:24 UTC by knoellle

## Introduced Changes

Hybrid alignment was completely bronek when approaching a target position from the opposite direction. See associated issue for problem details.

This PR changes the hybrid alignment behavior to slowly reduce the allowed deviation from the target orientation based on the distance to the target.
Effectively, there is a cone of allowed orientations around the target orientations which shrinks when the robot gets closer.
The requested orientation then the current robot orientation (Identity in Ground), clamped to this allowed region.

Fixes #643 

## ToDo / Known Issues

## Ideas for Next Iterations (Not This PR)

## How to Test

Set up game with at least a kick off striker and a game controller running.
After the striker scores a goal, it runs back to the kick off position, if the robot crosses the X axis of the target position within the hybrid align distance, it should no longer try to turn the other way and get stuck.
In every other situation, it should behave just like before.

2024-03-23 17:37 UTC, oleflb requested changes
Nice, great improvement in the hybrid alignment! Just one remark on the testcase.

2024-03-23 17:37 UTC, oleflb commented on crates/control/src/behavior/walk_to_pose.rs
> +            assert_relative_eq!(
also compare sign here? (or separate test)

2024-03-24 15:45 UTC, knoellle commented on crates/control/src/behavior/walk_to_pose.rs
> +            assert_relative_eq!(
Done

2024-03-26 16:59 UTC, oleflb approved these changes
:+1:

2024-03-26 17:15 UTC, merged