Update game controller messages and consequences
HULKs/hulk pull request #835
Opened 2024-04-14 20:27 UTC by MaikRe

## Introduced Changes

Uses newest game controller headers and deals with illegal motion in initial

Fixes #834 

## ToDo / Known Issues

## Ideas for Next Iterations (Not This PR)

## How to Test

Using the newest game controller and only after #806 is merged, give the robot a ready signal  for a "false positive". 
Penalize the robot with motion in initial from the newest game controller. The robot should keep its localization

2024-04-14 20:46 UTC, MaikRe commented
All of the checks and tests come up clean on my machine, but the CI clearly doesn't like me. I would like to look at this with someone who knows a little more than me about how the code generation for the game controller bindings works.

2024-04-16 13:02 UTC, schmidma requested changes
one very minor style thing ;)

2024-04-16 13:02 UTC, schmidma commented on crates/control/src/localization.rs
> +                    | Some(Penalty::IllegalMotionInInitial { remaining: _ }) => {
```suggestion
                    Some(Penalty::IllegalMotionInSet { .. })
                    | Some(Penalty::IllegalMotionInInitial { ..  }) => {
```

2024-04-16 13:23 UTC, schmidma approved these changes

2024-04-16 13:26 UTC, merged