Create Profile with LTO, use it for pregame
HULKs/hulk pull request #85
Opened 2023-01-30 14:29 UTC by schmidma

## Introduced Changes

This PR creates an additional build profile `release-lto`.
This profile enables Link-Time-Optimization (LTO).

I did not do detailed benchmarks, but at least the binary size reduces drastically:

| profile       | size |
|---------------|----:|
| `incremental` |     15M  |
| `release`     | 13M  |
| `release-lto` | 9.3M |

Pepsi uses this profile by default for pregame scenarios.

## ToDo / Known Issues

none

## Ideas for Next Iterations (Not This PR)

none

## How to Test

compile and upload (with or without `--profile release-lto`)

2023-01-30 19:16 UTC, knoellle requested changes
IMHO, the 6MB binary size saving isn't all that important and I would prefer not to massively increase link time for unknown runtime performance benefits.
LTO takes a looong time, so I would like to see some tangible benefits before merging this.

2025-05-08 11:54 UTC, oleflb commented
Agreeing with @knoellle here. What is your take on this @schmidma? Please close if you agree

2025-05-13 09:26 UTC, schmidma commented
hmmm... we probably have to benchmark the effect on our runtime. @oleflb up to you to decide whether this an issue we should tackle this season. If not, feel free to close this PR and open an issue to investigate the benefits of enabling LTO or even PGO

2026-06-15 10:51 UTC, schmidma commented
postponed

2026-06-15 10:51 UTC, closed without merging