Webots Improvements
HULKs/hulk pull request #92
Opened 2023-02-06 16:16 UTC by MaikRe

## Introduced Changes

Improves realism of Webots simulation as compared to SMD conditions.
Sets Webots location in pepsi and adds corresponding default configuration file.
Includes automatic updates of world file to Webots 2023a.

Fixes #

Collision meshes in hands, feet and shoulders.
Enabled self collision to improve standup front so that NAO no longer clips through its own hands.
Modified walking engine parameters for webots.

2023-02-11 06:00 UTC, h3ndrk requested changes
Thanks for your contribution!

I have some minor remarks. Feel free to implement/apply the requested changes or discuss.

I will test the new things in Webots after you added the "How to test" section, so that I know what to look for.

2023-02-11 22:32 UTC, MaikRe commented on etc/configuration/webots_location
> +/home/maik/TUHH/hulk/etc/configuration/webots
That symlink was created using the 'pepsi location set <target> <location>' command and as far as I understand it is necessary for pepsi build to use the correct config file when building for webots

2023-02-11 22:35 UTC, MaikRe commented on webots/worlds/penalized.wbt
> -#VRML_SIM R2022b utf8
This was added automatically when saving the proto file for webots 2023a, which as far as I was told is the current version we are working with

2023-02-11 22:36 UTC, MaikRe commented on etc/configuration/webots/default.json
> +}
Will do

2023-02-22 19:52 UTC, MaikRe commented on etc/configuration/webots_location
> +/home/maik/TUHH/hulk/etc/configuration/webots
symlink was changed to relative :)

2023-02-22 19:52 UTC, MaikRe commented on webots/worlds/penalized.wbt
> -#VRML_SIM R2022b utf8
jpg has been removed

2023-02-22 19:52 UTC, h3ndrk requested changes

2023-02-22 19:52 UTC, h3ndrk commented on webots/protos/NAO.proto
> +        #}
Remove instead of commenting out?

2023-02-22 19:54 UTC, MaikRe commented on webots/protos/NAO.proto
> +        #}
Done!

2023-02-22 20:38 UTC, h3ndrk approved these changes
Thank you very much for your contribution! :tada:

2023-02-22 20:42 UTC, merged