Fix parallel camera access die zweite
HULKs/hulk pull request #978
Opened 2024-04-24 16:59 UTC by oleflb

## Introduced Changes

Fixes the camera access bug. Also some minor refactoring in the camera, to remove one layer of interior mutability.

Fixes #961 
Fixes #736

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test

- Upload to NAO (should never crash)
- check vision recordings, should never process same frame twice

2024-04-25 05:36 UTC, h3ndrk commented on crates/hulk_nao/src/camera.rs
Could you please document somewhere what the intended semantics, i.e., the contract, are s.t. we can review and check it against that?

2024-05-04 12:15 UTC, oleflb commented on crates/hulk_nao/src/camera.rs
Done

2024-05-11 09:34 UTC, h3ndrk requested changes

2024-05-11 09:34 UTC, h3ndrk commented on crates/hulk_nao/src/camera.rs
> +    image_sender: Sender<Option<YCbCr422Image>>,
Why is the item type `Option`? Did I overlook the case where you send a `None`? Can we remove the `Option`?

2024-05-11 09:34 UTC, h3ndrk commented on crates/hulk_nao/src/camera.rs
> +        };
Isn't there a monadic way of expressing this `let Some else`? Like `unwrap_or` or `or_else`. I remember some method for converting a `None` into a `Err(...)`. 🤔

```suggestion
        let camera = self.camera.as_mut().ok_or_else(|| eyre!("camera does not exist"))?;
```

2024-05-11 09:34 UTC, h3ndrk commented on crates/hulk_nao/src/camera.rs
> +    camera: Mutex<CameraHardware>,
Talked about this, it is one mutex per camera.

2024-05-11 09:34 UTC, h3ndrk commented on crates/hulk_nao/src/camera.rs
> +    image_sender: Sender<Option<YCbCr422Image>>,
The channel needs to be initialized with something that is defaultable.

2024-05-11 09:56 UTC, h3ndrk approved these changes

2024-05-11 10:00 UTC, merged