HuLA DBus interface for efficiently querying battery status and IDs
HULKs/hulk pull request #99
Opened 2023-02-09 19:24 UTC by julianschuler

## Introduced Changes

This PR adds a DBus interface to HuLA for efficiently querying the battery status and body/head IDs.

This reduces the load of the aliveness service on HuLA since it only interacts with HuLA when actual requests are received.

## ToDo / Known Issues

It currently uses the session DBus, thus will only work after the first user login (only then the session bus is started) and restarting aliveness.
This will be replaced with the system DBus as soon as the correct permissions handling is determined.

## Ideas for Next Iterations (Not This PR)

None yet.

## How to Test

First, ssh into a NAO and stop the aliveness and hula services using

```
systemctl stop aliveness
systemctl stop hula
```

Source the SDK, build both `tools/hula` and `tools/aliveness` and execute them on a NAO.

Use `./pepsi aliveness` to check that everything works as expected.

2023-02-09 20:41 UTC, h3ndrk commented
Remark regarding the session/system bus: We may run HULK and HULA as `root` in the future. But not yet determined.

2023-02-18 13:10 UTC, schmidma requested changes
This looks sooooo fancy :heart_eyes: 

I have only some minor remarks...

2023-02-18 13:10 UTC, schmidma commented on tools/aliveness/src/robot_info.rs
> +        }
```suggestion
        self.proxy.battery().await.ok().and_then(Option::from)
```

2023-02-21 15:18 UTC, julianschuler commented on tools/aliveness/src/robot_info.rs
> +// It is unfortunately not possible to deduplicate those values since they are literals
Should I remove the comment because the explanation is obvious or is there a different reason for its removal?

2023-02-21 15:34 UTC, julianschuler commented on tools/hula/Cargo.toml
> +zbus = "3.7.0"
Alright, fixed.

2023-02-21 15:35 UTC, julianschuler commented on tools/hula/proxy/src/dbus.rs
> +                Optional::from(Some(String::from_utf8(head_id).unwrap()))
Thanks, fixed.

2023-02-21 15:35 UTC, julianschuler commented on tools/hula/proxy/src/dbus.rs
> +        match self.shared_state.lock().unwrap().configuration {
Thanks, fixed

2023-02-21 15:35 UTC, julianschuler commented on tools/hula/proxy/src/dbus.rs
> +        match self.shared_state.lock().unwrap().configuration {
Thanks for the hint, fixed.

2023-02-21 15:35 UTC, julianschuler commented on tools/hula/proxy/src/idle.rs
> +    shared_state: &Arc<Mutex<SharedState>>,
Thanks, fixed.

2023-02-21 15:36 UTC, julianschuler commented on tools/aliveness/src/robot_info.rs
> +        }
Thanks, fixed.

2023-02-21 15:40 UTC, julianschuler commented on tools/aliveness/Cargo.toml
> +version = "0.2.0"
I think this is appropriate since it uses a different feature set. Let's discuss this in the dev-meeting.

2023-02-21 16:24 UTC, h3ndrk commented on tools/aliveness/src/robot_info.rs
> +// It is unfortunately not possible to deduplicate those values since they are literals
If you need a comment, don't document the what, document the why. If the why is explained by code, remove the comment.

In this case, I vote for removal. Or explain why you need to duplicate.

2023-02-21 18:14 UTC, julianschuler commented on tools/aliveness/src/robot_info.rs
> +// It is unfortunately not possible to deduplicate those values since they are literals
Thank you for your answer! I removed the comment now.

2023-02-22 16:31 UTC, julianschuler commented on tools/hula/proxy/src/main.rs
> +    let _handle = serve_dbus(shared_state.clone());
Thanks, fixed.

2023-02-22 17:22 UTC, schmidma approved these changes

2023-02-22 17:25 UTC, merged