Time is of the Essence
HULKs/hulk pull request #990
Opened 2024-05-03 19:28 UTC by schmidma

## Introduced Changes

![](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmxoZGt6ZzYxNGVoMDRkaGtxdmc4OWE1NDdwZ21kdThoMTZiencwNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/bkcYElQQVstXFsr4yL/giphy.gif)

Tags data with "now"... whatever that means

Based on #987 

## ToDo / Known Issues

none

## Ideas for Next Iterations (Not This PR)

none

## How to Test

not yet...

2024-07-05 20:45 UTC, schluis commented
Please remove the dependency on #1089, then we can merge this (otherwise cool pr 😉). @oleflb would be willing to support you on this.

2024-07-13 12:00 UTC, oleflb requested changes
Things I noticed during testing:
- Behavior Simulator Panel crashes twix when opened if connected to nao
- When subscribing the same path two times, the second subscription does not receive an update of the value. This is very noticeable for parameters. Try opening 2 map panels, the second map panel does not receive field dimensions until you set it via parameters panel

2024-07-13 12:01 UTC, oleflb commented on crates/communication/src/client.rs
> +        // TODO: properly shut down open tasks, like the protocol
todo?

2024-07-14 06:42 UTC, schmidma commented on crates/linear_algebra/src/framed.rs
> +    collections::HashSet,
We do not need the additional guarantees of `BTreeSet` we only need some storage for our strings. Thus `HashSet` is the correct choice.

2024-07-14 06:42 UTC, schmidma commented on crates/path_serde/src/implementation.rs
> -    collections::BTreeSet,
see above

2024-07-14 06:49 UTC, schmidma commented on crates/hulk_replayer/src/replayer.rs
By mistake. Good catch. The reason for this is, that in some intermediate state of the implementation, the `communication_address` in the `framework.json` was not an `Option` anymore. Therefore this fallback was not necessary. I reverted this change, and also added an info log that we are falling back to the default communication addresses.

2024-07-14 06:58 UTC, schmidma commented on tools/twix/src/main.rs
> +        let nao = Arc::new(Nao::new(format!("ws://{address}:1337")));
Yes. Added a
```
.map(|address| {
    NaoAddress::from_str(&address)
        .map(|nao| nao.to_string())
        .unwrap_or(address)
})
```

2024-07-14 07:00 UTC, schmidma commented on crates/communication/src/client.rs
> +        // TODO: properly shut down open tasks, like the protocol
yes, this kinda actually is a todo. We currently drop some of the task to the floor if you close twix... I can open an issue for that and suggest to not fix this in this PR, as this is mostly not necessary. The server can handle breaking connections etc...

2024-07-14 07:01 UTC, schmidma commented on crates/communication/src/server/acceptor.rs
> +        // TODO: keep the handle to shutdown the clients
Not a Todo anymore, forgot to remove that. Thanks :+1:

2024-07-14 07:02 UTC, schmidma commented on crates/communication/src/server/source.rs
> +    // TODO: use subscription handle to start subscription, if the successful subscription response
Yes, this still is a Todo. But also an optional one. This might speed up the server even more. I can open an issue for that.

2024-07-14 07:07 UTC, schmidma commented
Regarding the missing updates in parameter panels:

Yes, this indeed is a bug... I'm currently not entirely sure how to fix that. The very ugly work-around would be to reconnect :D Then all subscribers get the update. The problem is, that I deduplicate the subscriptions and the second parameter panel never actually does communication with the nao as it is already subscribed.

I see two possible solutions: re-request data from the nao, or store the latest value locally and forward it to the client...

I'll think about it

2024-07-14 15:44 UTC, schmidma commented
> Regarding the missing updates in parameter panels:
> 
> Yes, this indeed is a bug... I'm currently not entirely sure how to fix that. The very ugly work-around would be to reconnect :D Then all subscribers get the update. The problem is, that I deduplicate the subscriptions and the second parameter panel never actually does communication with the nao as it is already subscribed.
> 
> I see two possible solutions: re-request data from the nao, or store the latest value locally and forward it to the client...
> 
> I'll think about it

I chose the way to re-request the value from the server. Implemented in https://github.com/HULKs/hulk/pull/990/commits/b1bc89af26a28595b2097b0246690e9564846ac6

2024-07-15 09:38 UTC, oleflb reviewed
Finished code review, will test now

2024-07-15 10:05 UTC, schmidma commented on crates/communication/src/client.rs
> +        // TODO: properly shut down open tasks, like the protocol
#1189

2024-07-15 10:08 UTC, oleflb approved these changes
Nice :rocket:

2024-07-15 10:09 UTC, schmidma commented on crates/communication/src/server/source.rs
> +    // TODO: use subscription handle to start subscription, if the successful subscription response
#1190

2024-07-15 10:12 UTC, merged